- name: Check if amazon-cloudwatch-agent is installed
  command: dpkg-query -W amazon-cloudwatch-agent
  register: agent_package_check_deb
  failed_when: agent_package_check_deb.rc > 1
  changed_when: agent_package_check_deb.rc == 1

- name: Download amazon-cloudwatch-agent
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb
  when: agent_package_check_deb.rc == 1

- name: Install amazon-cloudwatch-agent
  apt:
    deb: /tmp/amazon-cloudwatch-agent.deb
  when: agent_package_check_deb.rc == 1

- name: Add amazon-cloudwatch-agent config
  copy:
    src: ../files/config.json
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
    owner: root
    group: root
    mode: '0755'

- name: Start amazon-cloudwatch-agent
  command: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
